# Generated by Django 6.0.7 on 2026-08-05 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('work', 'Work'), ('rest', 'Rest')], max_length=4)),
                ('duration', models.PositiveIntegerField()),
                ('repeat', models.PositiveIntegerField(default=0)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='timer.timer')),
            ],
        ),
    ]
