# Generated by Django 6.0.7 on 2026-08-05 01:01

from django.db import migrations

def create_timers(apps, schema_editor):
    Timer = apps.get_model('timer', 'timer')
    User = apps.get_model('accounts', 'user')
    
    u = User.objects.filter(email='user1@email.com')
    
    if u:   
        Timer.objects.get_or_create(title='Timer1', user=u.first())
        
def delete_timers(apps, schema_editor):
    Timer = apps.get_model('timer', 'timer')
    User = apps.get_model('accounts', 'user')
    
    u = User.objects.filter(email='user1@email.com')
    
    if u:   
        try:
            Timer.objects.get(title='Timer1', user=u.first()).delete()
        except:
            ...


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_users'),
        ('timer', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_timers, delete_timers)
    ]
