# Generated by Django 6.0.7 on 2026-08-05 01:05

from django.db import migrations
from ..enums import Type

def create_intervals(apps, schema_editor):
    Timer = apps.get_model('timer', 'timer')
    User = apps.get_model('accounts', 'user')
    Interval = apps.get_model('timer', 'interval')
        
    u = User.objects.filter(email='user1@email.com')
        
    if u:   
        t = Timer.objects.filter(title='Timer1', user=u.first())
        
        if t:
            Interval.objects.get_or_create(
                timer=t.first(), 
                name='Interval1', 
                type=Type.WORK,
                duration=1000,
                )
            
def delete_intervals(apps, schema_editor):
    Timer = apps.get_model('timer', 'timer')
    User = apps.get_model('accounts', 'user')
    Interval = apps.get_model('timer', 'interval')
        
    u = User.objects.filter(email='user1@email.com')
        
    if u:   
        t = Timer.objects.filter(title='Timer1', user=u.first())
        
        if t:
            try:  
                Interval.objects.get(
                    timer=t.first(), 
                    name='Interval1', 
                    type=Type.WORK,
                    duration=1000,
                    ).delete()
            except:
                ...


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_create_timers'),
    ]

    operations = [
        migrations.RunPython(create_intervals, delete_intervals)
    ]
