# Generated by Django 6.0.7 on 2026-08-05 00:53

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_users(apps, schema_editor):
    User = apps.get_model('accounts', 'user')
    
    u, created = User.objects.get_or_create(email='user1@email.com')
    
    if created:
        u.password = make_password('123')
        u.save()
        
def delete_users(apps, shema_editor):
    User = apps.get_model('accounts', 'user')
    
    try:
        User.objects.get(email='user1@email.com').delete()
    except:
        ...


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_users, delete_users)
    ]
